### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by bfpimentel** [bfpimentel/news-app#7]
# Feature Roadmap V1
- [x] Architecture
  - [x] BaseFragment
  - [x] BaseViewModel
  - [x] UseCase Interface
---
- [x] Git
  - [x] Each feature on its own branch
---
- [x] CI
  - [x] Actions? 
  - [x] ~~Other?~~ 
  - [x] Test Coverage
  - [x] Static Code Analysis
---
- [ ] Project
  - [x] Modular Features
  - [x] Jetpack Navigation
  - [x] View Binding
  - [x] Unit Tests
  - [x] Networking
  - [ ] Pagination
  - [ ] Instrumented Tests
---
- [ ] Features
  - [x] Navigator
  - [ ] News Feed
  - [ ] Search
  - [ ] Profile
  - [ ] Read News
  - [ ] Change Feed Settings
